# H2 ?????? ??
spring.application.name=fifthWeek
spring.datasource.url=jdbc:h2:mem:Ecommerce
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 ?? ??? (? ?????? H2 DB? ??? ? ?? ?)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA ?? - DDL ?? ?? (?? ? none?? ??)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ??? ?? ?? ???? ????? ??
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:firstData.sql


# Kafka server address
spring.kafka.bootstrap-servers=localhost:9092

# Producer setting
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer setting
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
