-- MEMBER INFO
INSERT INTO MEMBER_INFO (MEMBER_ID, MEMBER_BALANCE) VALUES(1, 100000);
INSERT INTO MEMBER_INFO (MEMBER_ID, MEMBER_BALANCE) VALUES(2, 200000);
INSERT INTO MEMBER_INFO (MEMBER_ID, MEMBER_BALANCE) VALUES(3, 300000);

-- PRODUCT INFO
INSERT INTO PRODUCT_INFO (PRODUCT_ID, PRODUCT_NAME) VALUES(1, '모니터');
INSERT INTO PRODUCT_INFO (PRODUCT_ID, PRODUCT_NAME) VALUES(2, '컴퓨터');
INSERT INTO PRODUCT_INFO (PRODUCT_ID, PRODUCT_NAME) VALUES(3, '선풍기');
INSERT INTO PRODUCT_INFO (PRODUCT_ID, PRODUCT_NAME) VALUES(4, '키보드');
INSERT INTO PRODUCT_INFO (PRODUCT_ID, PRODUCT_NAME) VALUES(5, '핸드폰');
INSERT INTO PRODUCT_INFO (PRODUCT_ID, PRODUCT_NAME) VALUES(6, '마우스');
INSERT INTO PRODUCT_INFO (PRODUCT_ID, PRODUCT_NAME) VALUES(7, '전화기');
INSERT INTO PRODUCT_INFO (PRODUCT_ID, PRODUCT_NAME) VALUES(8, '의자');
INSERT INTO PRODUCT_INFO (PRODUCT_ID, PRODUCT_NAME) VALUES(9, '세탁기');
INSERT INTO PRODUCT_INFO (PRODUCT_ID, PRODUCT_NAME) VALUES(10, 'TV');

-- PRODUCT OPTION INFO
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(1, 1, '21인치', 10, 40000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(1, 2, '24인치', 10, 50000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(1, 3, '28인치', 10, 60000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(1, 4, '34인치', 10, 70000);

INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(2, 1, 'i3', 10, 100000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(2, 2, 'i5', 10, 150000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(2, 3, 'i7', 10, 200000);

INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(3, 1, '3중날', 10, 30000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(3, 2, '4중날', 10, 40000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(3, 3, '5중날', 10, 50000);

INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(4, 1, '청축', 10, 10000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(4, 2, '적축', 10, 20000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(4, 3, '갈축', 10, 30000);

INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(5, 1, '아이폰', 10, 100000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(5, 2, '갤럭시', 10, 100000);

INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(6, 1, '레이저', 10, 5000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(6, 2, '로지텍', 10, 5000);

INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(7, 1, '무선', 10, 5000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(7, 2, '유선', 10, 5000);

INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(8, 1, '인조가죽', 10, 30000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(8, 2, '매쉬', 10, 50000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(8, 3, '가죽', 10, 70000);

INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(9, 1, '세탁기만', 10, 100000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(9, 2, 'AI세탁기', 10, 150000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(9, 3, '세탁기와건조기', 10, 200000);

INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(10, 1, '40인치', 10, 150000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(10, 2, '50인치', 10, 200000);
INSERT INTO PRODUCT_OPTION_INFO (PRODUCT_ID, PRODUCT_OPTION_ID, PRODUCT_OPTION_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE) VALUES(10, 3, '60인치', 10, 250000);

-- Order Info

INSERT INTO ORDER_INFO (ORDER_ID, MEMBER_ID, PRODUCT_LIST, PRODUCT_OPTION_LIST, QUANTITY_LIST) VALUES (1, 1, '1,1,1', '1,1,1,', '10,10,10');
INSERT INTO ORDER_INFO (ORDER_ID, MEMBER_ID, PRODUCT_LIST, PRODUCT_OPTION_LIST, QUANTITY_LIST) VALUES (2, 1, '1,2,3', '1,1,1', '1,1,1');




-- Add History
INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (1, 1, 1, '2024-10-01 13:00:00');
INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (1, 2, 2, '2024-10-01 13:00:00');
INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (1, 3, 3, '2024-10-01 13:00:00');

INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (2, 1, 5, '2024-10-02 13:00:00');
INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (2, 2, 10, '2024-10-02 13:00:00');
INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (2, 3, 15, '2024-10-02 13:00:00');

INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (3, 1, 10, '2024-10-04 13:00:00');
INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (3, 2, 20, '2024-10-04 13:00:00');
INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (3, 3, 30, '2024-10-04 13:00:00');

INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (4, 1, 100, '2024-10-03 13:00:00');
INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (4, 2, 200, '2024-10-03 13:00:00');
INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (4, 3, 300, '2024-10-03 13:00:00');

INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (5, 1, 100, '2024-12-03 13:00:00');
INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (5, 2, 200, '2024-12-03 13:00:00');
INSERT INTO PRODUCT_HISTORY(PRODUCT_ID, PRODUCT_OPTION_ID, INDE_AMOUNT, CREATED_AT) VALUES (5, 3, 300, '2024-12-03 13:00:00');
